### ISSUE TITLE
what's with this show action?

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/routing-nested-resources-reading#10]
Instructions say:

> Let's update index and show for the new routes:
 # controllers\posts_controller.rb
  
   def index
     if params[:author_id]
       @posts = Author.find(params[:author_id]).posts
     else
       @posts = Post.all
     end
   end
  
   def show
     if params[:author_id]
       @post = Post.find(params[:id])
     else
       @post = Post.find(params[:id])
     end
   end
  
   def new
     # ...

Now why in the world would we setup a show method like this? `if x, then do y, else do y`

It seems like the `if params[:author_id]` is completely pointless unless I'm missing something.

**Comment by mendelB** [comment]
Thanks @jessenovotny! fixed with #11
