### ISSUE TITLE
Completed but not updating

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/routing-nested-resources-reading#15]
I completed the readme but it is not showing that I have completed it.

**Comment by rfenix3** [comment]
Same issue posted by earlier user. Completed the readme. Clicked finshed reading but not updating/showing that I have completed it. Is it because I clicked finished first before doing 'learn submit'?

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
