### ISSUE TITLE
Can't open lab via Learn IDE

### ISSUE THREAD

**Issue by derrickbozich** [learn-co-curriculum/routing-nested-resources-reading#16]
The page for this lab doesn't have a link to open via learn IDE. I manually forked and cloned, passed all local tests, and pushed up to GitHub via atom, but don't know how to get my learn.co profile to know

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
