### ISSUE TITLE
Paths are not properly named.

### ISSUE THREAD

**Issue by veloblank** [learn-co-curriculum/routing-nested-resources-reading#18]
In the README:

*Let's reload ```/posts``` and click on an author name. We should be taken to ```/author/id/posts```.

Great! Now our URLs properly reflect the relationship of our resources and read almost like an English sentence: ```author/1/posts ``` = "author number one's posts."*

The nested routes should be ```/authors/id/posts``` and ```authors/1/posts```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
