### ISSUE TITLE
Gemfile incompatible with ruby 2.6.1

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/routing-nested-resources-reading#23]
__Gemfile needs the following updates:__

1. Remove rails version from rails gem
2. Change `gem 'sqlite3'` to `gem 'sqlite3', '~> 1.3.7`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
