### ISSUE TITLE
Can't Follow Along

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/routing-nested-resources-reading#24]
Using the code provided, and after running `rake db:seed` when I'm in the Rails server, it's still telling me that an author with an ID of 1 can't be found.

None of the authors' names are linked to their show pages, and when I go to /authors/1/posts, it's showing me an index of all articles.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information, I'd be happy to take a second look!

As always, thanks for contributing! 💙
