### ISSUE TITLE
Confusing and possibly incorrect example code.

### ISSUE THREAD

**Issue by dukeoflaser** [learn-co-curriculum/routing-nested-resources-reading#5]
The #show action for controllers\posts_controller.rb  in the readme example is as follows. I was advised by the learn-co staff to raise an issue over this as it *curious*. It appears to be a redundant if/else statement.

```
  def show
    if params[:author_id]
      @post = Post.find(params[:id])
    else
      @post = Post.find(params[:id])
    end
  end
```

**Comment by mendelB** [comment]
Thanks @dukeoflaser! fixed with #11
